server:
  port: 9999
spring:
  application:
    name: short-message-server
eureka:
  instance:
    instance-id: short-message-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/