server:
  port: 8002
spring:
  application:
    name: edu-stu-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    publisher-returns: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.edu.stu.domain


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    enabled: false
  instance:
    hostname: edu-stu-server8002
    instance-id: edu-stu-server8002
    prefer-ip-address: true

