server:
  port: 7999
spring:
  application:
    name: cloud-config

  cloud:
    config:
      server:
        git:
          uri: git@github.com:Vinces007/springCloud-config.git
          search-paths:
            - springCloud-onfig
      label: master

eureka:
  client:
    enabled: false
  instance:
    instance-id: cloud-config

